### ISSUE TITLE
UI Thread Exception When Cloning Repository

### ISSUE THREAD

**Issue by twilroad** [shiftkey/ReactiveGit#18]
I writed the same code like project ReactiveGit.Demo,but when cloning a repository,a exception throw like this:
![20150402131721](https://cloud.githubusercontent.com/assets/5193767/6958281/0b8ea18c-d93c-11e4-801c-b59753d3a67e.png)

I donot kown how could this happen,please help!

**Comment by shiftkey** [comment]
@windcold could you attach the raw exception text so I can have a go at translating this?

Also, there should be an `InnerException` which might explain the underlying problem.

**Comment by windcold** [comment]
@shiftkey,I uploaded,https://github.com/windcold/ReactiveGitTest.git,thank you again!

**Comment by shiftkey** [comment]
I couldn't trigger the `TargetInvocationException`, but the details here suggest that something isn't being scheduled on the main thread:

```
System.Windows.Threading.Dispatcher.VerifyAccess() System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
```

This is likely something with how the ReactiveUI callbacks are configured. If you're manipulating a `ReactiveList`, ensure that it's running on the main thread.

Also, I found a possibly related libgit2sharp exception not being surfaced correctly by the library.

When selecting an folder to clone to, if you choose a non-empty directory you get this error:

![screen shot 2015-04-02 at 3 08 32 pm](https://cloud.githubusercontent.com/assets/359239/6964507/2b820782-d94a-11e4-8182-6232fd252e59.png)

The workaround is to ensure you choose an empty directory for the `ObservableRepository.Clone`.

This then started showing the progress for the user:

![screen shot 2015-04-02 at 3 04 41 pm](https://cloud.githubusercontent.com/assets/359239/6964501/0abf3678-d94a-11e4-931c-ad8f1c30f997.png)

And it completes the clone:

![screen shot 2015-04-02 at 3 24 02 pm](https://cloud.githubusercontent.com/assets/359239/6964811/f0f4ea78-d94c-11e4-9b98-784d31c0e1d7.png)

I anticipate a whole bunch of changes to the API due to the discussion in #16, but I'll leave this open for now to re-test this will surface the right correction.

**Comment by windcold** [comment]
@shiftkey , you mean that, my codes works well on your computer?that is very strange…
